### ISSUE TITLE
Endless signing in animation loop

### ISSUE THREAD

**Issue by strawberriesandcheese** [marcelgarus/murderers#88]
To reproduce (hopefully): 
1) Click "Sign in anonymously". 
2) Decide you rather wait for the fix on Google account sign in after you see that you have to put in your email address.
3) Click back.
4) Watch the endless circle animation loop that happens in the place where the "sign in anonymously" option was originally.

**Comment by strawberriesandcheese** [comment]
*signing

**Comment by marcelgarus** [comment]
Yup, so true. Probably relates to #9, but I'll leave it here.

**Comment by marcelgarus** [comment]
Should work now but still needs to be sent to the store.

**Comment by marcelgarus** [comment]
Fixed.
